### ISSUE TITLE
Trying build fail. need more specfic build doc.

### ISSUE THREAD

**Issue by wanghui22718** [ProfessorNavigator/communist#2]

**Comment by wanghui22718** [comment]
Try build with msys2, ubuntu 20.04LTS, ubuntu 22.04LTS, all failed
very interested with this projec

**Comment by ProfessorNavigator** [comment]
> Try build with msys2, ubuntu 20.04LTS, ubuntu 22.04LTS, all failed very interested with this projec

Gtkmm 4.0 is absent in main Ubuntu repositories, as far as I now, so may be you need to build gtkmm 4.0 with its' dependencies first. Could you provide build output for each system you've tried if possible?

**Comment by wanghui22718** [comment]
![image](https://user-images.githubusercontent.com/65607345/181454621-b4c30eb5-1d10-4d0d-ab02-bec8980685ae.png)

**Comment by ProfessorNavigator** [comment]
As I wrote - you need libgtkmm-4.0. It is absent in main Ubuntu repositories, so probably you need to build it from source by yourself. Unfortunately I can not suggest you any other decision, because I am not familiar with Ubuntu very much. I prepared packages only for two distros: Arch Linux (https://aur.archlinux.org/packages/communist) and ALT Linux (https://cloud.mail.ru/public/tg6f/JZeMycdH5). Last one is not "official" (it is not in distro repositories), but it works.
